export const POSTCODES_SEARCH_REQUEST = "POSTCODES_SEARCH_REQUEST";
export const POSTCODES_SEARCH_SUCCESS = "POSTCODES_SEARCH_SUCCESS";
export const POSTCODES_SEARCH_ERROR = "POSTCODES_SEARCH_ERROR";
export const POSTCODES_DETAILS_REQUEST = "POSTCODES_DETAILS_REQUEST";
export const POSTCODES_DETAILS_SUCCESS = "POSTCODES_DETAILS_SUCCESS";
export const POSTCODES_DETAILS_ERROR = "POSTCODES_DETAILS_ERROR";
export const DASHBOARD_DRAWER_OPEN = "DASHBOARD_DRAWER_OPEN";